// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

import java.time.LocalDateTime;

public class ApiErrorResponseDTO {
    private LocalDateTime timestamp;
    private int status;
    private String error;
    private String message;
    private String path;


    @java.lang.SuppressWarnings("all")
    public static class ApiErrorResponseDTOBuilder {
        @java.lang.SuppressWarnings("all")
        private LocalDateTime timestamp;
        @java.lang.SuppressWarnings("all")
        private int status;
        @java.lang.SuppressWarnings("all")
        private String error;
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private String path;

        @java.lang.SuppressWarnings("all")
        ApiErrorResponseDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO.ApiErrorResponseDTOBuilder timestamp(final LocalDateTime timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO.ApiErrorResponseDTOBuilder status(final int status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO.ApiErrorResponseDTOBuilder error(final String error) {
            this.error = error;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO.ApiErrorResponseDTOBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO.ApiErrorResponseDTOBuilder path(final String path) {
            this.path = path;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public ApiErrorResponseDTO build() {
            return new ApiErrorResponseDTO(this.timestamp, this.status, this.error, this.message, this.path);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "ApiErrorResponseDTO.ApiErrorResponseDTOBuilder(timestamp=" + this.timestamp + ", status=" + this.status + ", error=" + this.error + ", message=" + this.message + ", path=" + this.path + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static ApiErrorResponseDTO.ApiErrorResponseDTOBuilder builder() {
        return new ApiErrorResponseDTO.ApiErrorResponseDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getTimestamp() {
        return this.timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public int getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public String getError() {
        return this.error;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public String getPath() {
        return this.path;
    }

    @java.lang.SuppressWarnings("all")
    public void setTimestamp(final LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final int status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setError(final String error) {
        this.error = error;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setPath(final String path) {
        this.path = path;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ApiErrorResponseDTO)) return false;
        final ApiErrorResponseDTO other = (ApiErrorResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getStatus() != other.getStatus()) return false;
        final java.lang.Object this$timestamp = this.getTimestamp();
        final java.lang.Object other$timestamp = other.getTimestamp();
        if (this$timestamp == null ? other$timestamp != null : !this$timestamp.equals(other$timestamp)) return false;
        final java.lang.Object this$error = this.getError();
        final java.lang.Object other$error = other.getError();
        if (this$error == null ? other$error != null : !this$error.equals(other$error)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$path = this.getPath();
        final java.lang.Object other$path = other.getPath();
        if (this$path == null ? other$path != null : !this$path.equals(other$path)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ApiErrorResponseDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getStatus();
        final java.lang.Object $timestamp = this.getTimestamp();
        result = result * PRIME + ($timestamp == null ? 43 : $timestamp.hashCode());
        final java.lang.Object $error = this.getError();
        result = result * PRIME + ($error == null ? 43 : $error.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $path = this.getPath();
        result = result * PRIME + ($path == null ? 43 : $path.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ApiErrorResponseDTO(timestamp=" + this.getTimestamp() + ", status=" + this.getStatus() + ", error=" + this.getError() + ", message=" + this.getMessage() + ", path=" + this.getPath() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public ApiErrorResponseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public ApiErrorResponseDTO(final LocalDateTime timestamp, final int status, final String error, final String message, final String path) {
        this.timestamp = timestamp;
        this.status = status;
        this.error = error;
        this.message = message;
        this.path = path;
    }
}
