// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

import com.certifyme.app.model.CertificationStatus;
import com.certifyme.app.model.RenewalStatus;
import java.time.LocalDateTime;

public class CertificationResponseDTO {
    private Long id;
    private String title;
    private String issuer;
    private String credentialId;
    private String url;
    private String remarks;
    private RenewalStatus renewalStatus;
    private CertificationStatus certificationStatus;
    private LocalDateTime issueDate;
    private LocalDateTime expiryDate;
    private LocalDateTime requestedOn;
    private LocalDateTime approvedOn;
    private LocalDateTime rejectedOn;
    private LocalDateTime lastReminderSent;
    private UserResponseDTO user;
    // Computed fields for frontend
    private Long daysUntilExpiry;
    private boolean renewalEligible;
    private String formattedIssueDate;
    private String formattedExpiryDate;

    @java.lang.SuppressWarnings("all")
    public CertificationResponseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getIssuer() {
        return this.issuer;
    }

    @java.lang.SuppressWarnings("all")
    public String getCredentialId() {
        return this.credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemarks() {
        return this.remarks;
    }

    @java.lang.SuppressWarnings("all")
    public RenewalStatus getRenewalStatus() {
        return this.renewalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public CertificationStatus getCertificationStatus() {
        return this.certificationStatus;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getIssueDate() {
        return this.issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getRequestedOn() {
        return this.requestedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getApprovedOn() {
        return this.approvedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getRejectedOn() {
        return this.rejectedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastReminderSent() {
        return this.lastReminderSent;
    }

    @java.lang.SuppressWarnings("all")
    public Long getDaysUntilExpiry() {
        return this.daysUntilExpiry;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRenewalEligible() {
        return this.renewalEligible;
    }

    @java.lang.SuppressWarnings("all")
    public String getFormattedIssueDate() {
        return this.formattedIssueDate;
    }

    @java.lang.SuppressWarnings("all")
    public String getFormattedExpiryDate() {
        return this.formattedExpiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public UserResponseDTO getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final UserResponseDTO user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssuer(final String issuer) {
        this.issuer = issuer;
    }

    @java.lang.SuppressWarnings("all")
    public void setCredentialId(final String credentialId) {
        this.credentialId = credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemarks(final String remarks) {
        this.remarks = remarks;
    }

    @java.lang.SuppressWarnings("all")
    public void setRenewalStatus(final RenewalStatus renewalStatus) {
        this.renewalStatus = renewalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setCertificationStatus(final CertificationStatus certificationStatus) {
        this.certificationStatus = certificationStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssueDate(final LocalDateTime issueDate) {
        this.issueDate = issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestedOn(final LocalDateTime requestedOn) {
        this.requestedOn = requestedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setApprovedOn(final LocalDateTime approvedOn) {
        this.approvedOn = approvedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setRejectedOn(final LocalDateTime rejectedOn) {
        this.rejectedOn = rejectedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastReminderSent(final LocalDateTime lastReminderSent) {
        this.lastReminderSent = lastReminderSent;
    }

    @java.lang.SuppressWarnings("all")
    public void setDaysUntilExpiry(final Long daysUntilExpiry) {
        this.daysUntilExpiry = daysUntilExpiry;
    }

    @java.lang.SuppressWarnings("all")
    public void setRenewalEligible(final boolean renewalEligible) {
        this.renewalEligible = renewalEligible;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormattedIssueDate(final String formattedIssueDate) {
        this.formattedIssueDate = formattedIssueDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setFormattedExpiryDate(final String formattedExpiryDate) {
        this.formattedExpiryDate = formattedExpiryDate;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CertificationResponseDTO)) return false;
        final CertificationResponseDTO other = (CertificationResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isRenewalEligible() != other.isRenewalEligible()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$daysUntilExpiry = this.getDaysUntilExpiry();
        final java.lang.Object other$daysUntilExpiry = other.getDaysUntilExpiry();
        if (this$daysUntilExpiry == null ? other$daysUntilExpiry != null : !this$daysUntilExpiry.equals(other$daysUntilExpiry)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$issuer = this.getIssuer();
        final java.lang.Object other$issuer = other.getIssuer();
        if (this$issuer == null ? other$issuer != null : !this$issuer.equals(other$issuer)) return false;
        final java.lang.Object this$credentialId = this.getCredentialId();
        final java.lang.Object other$credentialId = other.getCredentialId();
        if (this$credentialId == null ? other$credentialId != null : !this$credentialId.equals(other$credentialId)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$remarks = this.getRemarks();
        final java.lang.Object other$remarks = other.getRemarks();
        if (this$remarks == null ? other$remarks != null : !this$remarks.equals(other$remarks)) return false;
        final java.lang.Object this$renewalStatus = this.getRenewalStatus();
        final java.lang.Object other$renewalStatus = other.getRenewalStatus();
        if (this$renewalStatus == null ? other$renewalStatus != null : !this$renewalStatus.equals(other$renewalStatus)) return false;
        final java.lang.Object this$certificationStatus = this.getCertificationStatus();
        final java.lang.Object other$certificationStatus = other.getCertificationStatus();
        if (this$certificationStatus == null ? other$certificationStatus != null : !this$certificationStatus.equals(other$certificationStatus)) return false;
        final java.lang.Object this$issueDate = this.getIssueDate();
        final java.lang.Object other$issueDate = other.getIssueDate();
        if (this$issueDate == null ? other$issueDate != null : !this$issueDate.equals(other$issueDate)) return false;
        final java.lang.Object this$expiryDate = this.getExpiryDate();
        final java.lang.Object other$expiryDate = other.getExpiryDate();
        if (this$expiryDate == null ? other$expiryDate != null : !this$expiryDate.equals(other$expiryDate)) return false;
        final java.lang.Object this$requestedOn = this.getRequestedOn();
        final java.lang.Object other$requestedOn = other.getRequestedOn();
        if (this$requestedOn == null ? other$requestedOn != null : !this$requestedOn.equals(other$requestedOn)) return false;
        final java.lang.Object this$approvedOn = this.getApprovedOn();
        final java.lang.Object other$approvedOn = other.getApprovedOn();
        if (this$approvedOn == null ? other$approvedOn != null : !this$approvedOn.equals(other$approvedOn)) return false;
        final java.lang.Object this$rejectedOn = this.getRejectedOn();
        final java.lang.Object other$rejectedOn = other.getRejectedOn();
        if (this$rejectedOn == null ? other$rejectedOn != null : !this$rejectedOn.equals(other$rejectedOn)) return false;
        final java.lang.Object this$lastReminderSent = this.getLastReminderSent();
        final java.lang.Object other$lastReminderSent = other.getLastReminderSent();
        if (this$lastReminderSent == null ? other$lastReminderSent != null : !this$lastReminderSent.equals(other$lastReminderSent)) return false;
        final java.lang.Object this$formattedIssueDate = this.getFormattedIssueDate();
        final java.lang.Object other$formattedIssueDate = other.getFormattedIssueDate();
        if (this$formattedIssueDate == null ? other$formattedIssueDate != null : !this$formattedIssueDate.equals(other$formattedIssueDate)) return false;
        final java.lang.Object this$formattedExpiryDate = this.getFormattedExpiryDate();
        final java.lang.Object other$formattedExpiryDate = other.getFormattedExpiryDate();
        if (this$formattedExpiryDate == null ? other$formattedExpiryDate != null : !this$formattedExpiryDate.equals(other$formattedExpiryDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CertificationResponseDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isRenewalEligible() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $daysUntilExpiry = this.getDaysUntilExpiry();
        result = result * PRIME + ($daysUntilExpiry == null ? 43 : $daysUntilExpiry.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $issuer = this.getIssuer();
        result = result * PRIME + ($issuer == null ? 43 : $issuer.hashCode());
        final java.lang.Object $credentialId = this.getCredentialId();
        result = result * PRIME + ($credentialId == null ? 43 : $credentialId.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $remarks = this.getRemarks();
        result = result * PRIME + ($remarks == null ? 43 : $remarks.hashCode());
        final java.lang.Object $renewalStatus = this.getRenewalStatus();
        result = result * PRIME + ($renewalStatus == null ? 43 : $renewalStatus.hashCode());
        final java.lang.Object $certificationStatus = this.getCertificationStatus();
        result = result * PRIME + ($certificationStatus == null ? 43 : $certificationStatus.hashCode());
        final java.lang.Object $issueDate = this.getIssueDate();
        result = result * PRIME + ($issueDate == null ? 43 : $issueDate.hashCode());
        final java.lang.Object $expiryDate = this.getExpiryDate();
        result = result * PRIME + ($expiryDate == null ? 43 : $expiryDate.hashCode());
        final java.lang.Object $requestedOn = this.getRequestedOn();
        result = result * PRIME + ($requestedOn == null ? 43 : $requestedOn.hashCode());
        final java.lang.Object $approvedOn = this.getApprovedOn();
        result = result * PRIME + ($approvedOn == null ? 43 : $approvedOn.hashCode());
        final java.lang.Object $rejectedOn = this.getRejectedOn();
        result = result * PRIME + ($rejectedOn == null ? 43 : $rejectedOn.hashCode());
        final java.lang.Object $lastReminderSent = this.getLastReminderSent();
        result = result * PRIME + ($lastReminderSent == null ? 43 : $lastReminderSent.hashCode());
        final java.lang.Object $formattedIssueDate = this.getFormattedIssueDate();
        result = result * PRIME + ($formattedIssueDate == null ? 43 : $formattedIssueDate.hashCode());
        final java.lang.Object $formattedExpiryDate = this.getFormattedExpiryDate();
        result = result * PRIME + ($formattedExpiryDate == null ? 43 : $formattedExpiryDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CertificationResponseDTO(id=" + this.getId() + ", title=" + this.getTitle() + ", issuer=" + this.getIssuer() + ", credentialId=" + this.getCredentialId() + ", url=" + this.getUrl() + ", remarks=" + this.getRemarks() + ", renewalStatus=" + this.getRenewalStatus() + ", certificationStatus=" + this.getCertificationStatus() + ", issueDate=" + this.getIssueDate() + ", expiryDate=" + this.getExpiryDate() + ", requestedOn=" + this.getRequestedOn() + ", approvedOn=" + this.getApprovedOn() + ", rejectedOn=" + this.getRejectedOn() + ", lastReminderSent=" + this.getLastReminderSent() + ", daysUntilExpiry=" + this.getDaysUntilExpiry() + ", renewalEligible=" + this.isRenewalEligible() + ", formattedIssueDate=" + this.getFormattedIssueDate() + ", formattedExpiryDate=" + this.getFormattedExpiryDate() + ")";
    }
}
