// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class CertificationRequestDTO {
    @NotBlank(message = "Title is required")
    private String title;
    @NotBlank(message = "Issuer is required")
    private String issuer;
    private String credentialId;
    private String url;
    private String remarks;
    @NotNull(message = "Issue date is required")
    private LocalDateTime issueDate;
    private LocalDateTime expiryDate;

    @java.lang.SuppressWarnings("all")
    public CertificationRequestDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getIssuer() {
        return this.issuer;
    }

    @java.lang.SuppressWarnings("all")
    public String getCredentialId() {
        return this.credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemarks() {
        return this.remarks;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getIssueDate() {
        return this.issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssuer(final String issuer) {
        this.issuer = issuer;
    }

    @java.lang.SuppressWarnings("all")
    public void setCredentialId(final String credentialId) {
        this.credentialId = credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemarks(final String remarks) {
        this.remarks = remarks;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssueDate(final LocalDateTime issueDate) {
        this.issueDate = issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof CertificationRequestDTO)) return false;
        final CertificationRequestDTO other = (CertificationRequestDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$issuer = this.getIssuer();
        final java.lang.Object other$issuer = other.getIssuer();
        if (this$issuer == null ? other$issuer != null : !this$issuer.equals(other$issuer)) return false;
        final java.lang.Object this$credentialId = this.getCredentialId();
        final java.lang.Object other$credentialId = other.getCredentialId();
        if (this$credentialId == null ? other$credentialId != null : !this$credentialId.equals(other$credentialId)) return false;
        final java.lang.Object this$url = this.getUrl();
        final java.lang.Object other$url = other.getUrl();
        if (this$url == null ? other$url != null : !this$url.equals(other$url)) return false;
        final java.lang.Object this$remarks = this.getRemarks();
        final java.lang.Object other$remarks = other.getRemarks();
        if (this$remarks == null ? other$remarks != null : !this$remarks.equals(other$remarks)) return false;
        final java.lang.Object this$issueDate = this.getIssueDate();
        final java.lang.Object other$issueDate = other.getIssueDate();
        if (this$issueDate == null ? other$issueDate != null : !this$issueDate.equals(other$issueDate)) return false;
        final java.lang.Object this$expiryDate = this.getExpiryDate();
        final java.lang.Object other$expiryDate = other.getExpiryDate();
        if (this$expiryDate == null ? other$expiryDate != null : !this$expiryDate.equals(other$expiryDate)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof CertificationRequestDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $issuer = this.getIssuer();
        result = result * PRIME + ($issuer == null ? 43 : $issuer.hashCode());
        final java.lang.Object $credentialId = this.getCredentialId();
        result = result * PRIME + ($credentialId == null ? 43 : $credentialId.hashCode());
        final java.lang.Object $url = this.getUrl();
        result = result * PRIME + ($url == null ? 43 : $url.hashCode());
        final java.lang.Object $remarks = this.getRemarks();
        result = result * PRIME + ($remarks == null ? 43 : $remarks.hashCode());
        final java.lang.Object $issueDate = this.getIssueDate();
        result = result * PRIME + ($issueDate == null ? 43 : $issueDate.hashCode());
        final java.lang.Object $expiryDate = this.getExpiryDate();
        result = result * PRIME + ($expiryDate == null ? 43 : $expiryDate.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "CertificationRequestDTO(title=" + this.getTitle() + ", issuer=" + this.getIssuer() + ", credentialId=" + this.getCredentialId() + ", url=" + this.getUrl() + ", remarks=" + this.getRemarks() + ", issueDate=" + this.getIssueDate() + ", expiryDate=" + this.getExpiryDate() + ")";
    }
}
