// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

public class DashboardStatsDTO {
    private long totalCertifications;
    private long activeCertifications;
    private long expiringSoon;
    private long expiredCertifications;
    private long pendingRenewals;
    private double completionPercentage;


    @java.lang.SuppressWarnings("all")
    public static class DashboardStatsDTOBuilder {
        @java.lang.SuppressWarnings("all")
        private long totalCertifications;
        @java.lang.SuppressWarnings("all")
        private long activeCertifications;
        @java.lang.SuppressWarnings("all")
        private long expiringSoon;
        @java.lang.SuppressWarnings("all")
        private long expiredCertifications;
        @java.lang.SuppressWarnings("all")
        private long pendingRenewals;
        @java.lang.SuppressWarnings("all")
        private double completionPercentage;

        @java.lang.SuppressWarnings("all")
        DashboardStatsDTOBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder totalCertifications(final long totalCertifications) {
            this.totalCertifications = totalCertifications;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder activeCertifications(final long activeCertifications) {
            this.activeCertifications = activeCertifications;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder expiringSoon(final long expiringSoon) {
            this.expiringSoon = expiringSoon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder expiredCertifications(final long expiredCertifications) {
            this.expiredCertifications = expiredCertifications;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder pendingRenewals(final long pendingRenewals) {
            this.pendingRenewals = pendingRenewals;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO.DashboardStatsDTOBuilder completionPercentage(final double completionPercentage) {
            this.completionPercentage = completionPercentage;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DashboardStatsDTO build() {
            return new DashboardStatsDTO(this.totalCertifications, this.activeCertifications, this.expiringSoon, this.expiredCertifications, this.pendingRenewals, this.completionPercentage);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DashboardStatsDTO.DashboardStatsDTOBuilder(totalCertifications=" + this.totalCertifications + ", activeCertifications=" + this.activeCertifications + ", expiringSoon=" + this.expiringSoon + ", expiredCertifications=" + this.expiredCertifications + ", pendingRenewals=" + this.pendingRenewals + ", completionPercentage=" + this.completionPercentage + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static DashboardStatsDTO.DashboardStatsDTOBuilder builder() {
        return new DashboardStatsDTO.DashboardStatsDTOBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalCertifications() {
        return this.totalCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public long getActiveCertifications() {
        return this.activeCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public long getExpiringSoon() {
        return this.expiringSoon;
    }

    @java.lang.SuppressWarnings("all")
    public long getExpiredCertifications() {
        return this.expiredCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public long getPendingRenewals() {
        return this.pendingRenewals;
    }

    @java.lang.SuppressWarnings("all")
    public double getCompletionPercentage() {
        return this.completionPercentage;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalCertifications(final long totalCertifications) {
        this.totalCertifications = totalCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setActiveCertifications(final long activeCertifications) {
        this.activeCertifications = activeCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiringSoon(final long expiringSoon) {
        this.expiringSoon = expiringSoon;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiredCertifications(final long expiredCertifications) {
        this.expiredCertifications = expiredCertifications;
    }

    @java.lang.SuppressWarnings("all")
    public void setPendingRenewals(final long pendingRenewals) {
        this.pendingRenewals = pendingRenewals;
    }

    @java.lang.SuppressWarnings("all")
    public void setCompletionPercentage(final double completionPercentage) {
        this.completionPercentage = completionPercentage;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DashboardStatsDTO)) return false;
        final DashboardStatsDTO other = (DashboardStatsDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getTotalCertifications() != other.getTotalCertifications()) return false;
        if (this.getActiveCertifications() != other.getActiveCertifications()) return false;
        if (this.getExpiringSoon() != other.getExpiringSoon()) return false;
        if (this.getExpiredCertifications() != other.getExpiredCertifications()) return false;
        if (this.getPendingRenewals() != other.getPendingRenewals()) return false;
        if (java.lang.Double.compare(this.getCompletionPercentage(), other.getCompletionPercentage()) != 0) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DashboardStatsDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $totalCertifications = this.getTotalCertifications();
        result = result * PRIME + (int) ($totalCertifications >>> 32 ^ $totalCertifications);
        final long $activeCertifications = this.getActiveCertifications();
        result = result * PRIME + (int) ($activeCertifications >>> 32 ^ $activeCertifications);
        final long $expiringSoon = this.getExpiringSoon();
        result = result * PRIME + (int) ($expiringSoon >>> 32 ^ $expiringSoon);
        final long $expiredCertifications = this.getExpiredCertifications();
        result = result * PRIME + (int) ($expiredCertifications >>> 32 ^ $expiredCertifications);
        final long $pendingRenewals = this.getPendingRenewals();
        result = result * PRIME + (int) ($pendingRenewals >>> 32 ^ $pendingRenewals);
        final long $completionPercentage = java.lang.Double.doubleToLongBits(this.getCompletionPercentage());
        result = result * PRIME + (int) ($completionPercentage >>> 32 ^ $completionPercentage);
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DashboardStatsDTO(totalCertifications=" + this.getTotalCertifications() + ", activeCertifications=" + this.getActiveCertifications() + ", expiringSoon=" + this.getExpiringSoon() + ", expiredCertifications=" + this.getExpiredCertifications() + ", pendingRenewals=" + this.getPendingRenewals() + ", completionPercentage=" + this.getCompletionPercentage() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public DashboardStatsDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public DashboardStatsDTO(final long totalCertifications, final long activeCertifications, final long expiringSoon, final long expiredCertifications, final long pendingRenewals, final double completionPercentage) {
        this.totalCertifications = totalCertifications;
        this.activeCertifications = activeCertifications;
        this.expiringSoon = expiringSoon;
        this.expiredCertifications = expiredCertifications;
        this.pendingRenewals = pendingRenewals;
        this.completionPercentage = completionPercentage;
    }
}
