// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

import java.time.LocalDateTime;

public class NotificationResponseDTO {
    private Long id;
    private String title;
    private String message;
    private String type;
    private boolean isRead;
    private LocalDateTime createdAt;
    private LocalDateTime readAt;
    private Long certificationId; // Optional: Link to the specific certification
    private String certificationTitle; 

    @java.lang.SuppressWarnings("all")
    public NotificationResponseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getReadAt() {
        return this.readAt;
    }

    @java.lang.SuppressWarnings("all")
    public Long getCertificationId() {
        return this.certificationId;
    }

    @java.lang.SuppressWarnings("all")
    public String getCertificationTitle() {
        return this.certificationTitle;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setRead(final boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setReadAt(final LocalDateTime readAt) {
        this.readAt = readAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setCertificationId(final Long certificationId) {
        this.certificationId = certificationId;
    }

    @java.lang.SuppressWarnings("all")
    public void setCertificationTitle(final String certificationTitle) {
        this.certificationTitle = certificationTitle;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof NotificationResponseDTO)) return false;
        final NotificationResponseDTO other = (NotificationResponseDTO) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isRead() != other.isRead()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$certificationId = this.getCertificationId();
        final java.lang.Object other$certificationId = other.getCertificationId();
        if (this$certificationId == null ? other$certificationId != null : !this$certificationId.equals(other$certificationId)) return false;
        final java.lang.Object this$title = this.getTitle();
        final java.lang.Object other$title = other.getTitle();
        if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
        final java.lang.Object this$message = this.getMessage();
        final java.lang.Object other$message = other.getMessage();
        if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$createdAt = this.getCreatedAt();
        final java.lang.Object other$createdAt = other.getCreatedAt();
        if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
        final java.lang.Object this$readAt = this.getReadAt();
        final java.lang.Object other$readAt = other.getReadAt();
        if (this$readAt == null ? other$readAt != null : !this$readAt.equals(other$readAt)) return false;
        final java.lang.Object this$certificationTitle = this.getCertificationTitle();
        final java.lang.Object other$certificationTitle = other.getCertificationTitle();
        if (this$certificationTitle == null ? other$certificationTitle != null : !this$certificationTitle.equals(other$certificationTitle)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof NotificationResponseDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isRead() ? 79 : 97);
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $certificationId = this.getCertificationId();
        result = result * PRIME + ($certificationId == null ? 43 : $certificationId.hashCode());
        final java.lang.Object $title = this.getTitle();
        result = result * PRIME + ($title == null ? 43 : $title.hashCode());
        final java.lang.Object $message = this.getMessage();
        result = result * PRIME + ($message == null ? 43 : $message.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $createdAt = this.getCreatedAt();
        result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
        final java.lang.Object $readAt = this.getReadAt();
        result = result * PRIME + ($readAt == null ? 43 : $readAt.hashCode());
        final java.lang.Object $certificationTitle = this.getCertificationTitle();
        result = result * PRIME + ($certificationTitle == null ? 43 : $certificationTitle.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "NotificationResponseDTO(id=" + this.getId() + ", title=" + this.getTitle() + ", message=" + this.getMessage() + ", type=" + this.getType() + ", isRead=" + this.isRead() + ", createdAt=" + this.getCreatedAt() + ", readAt=" + this.getReadAt() + ", certificationId=" + this.getCertificationId() + ", certificationTitle=" + this.getCertificationTitle() + ")";
    }
}
