// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.dto;

import java.util.List;

public class PagedResponseDTO<T> {
    private List<T> content;
    private int page;
    private int size;
    private long totalElements;
    private int totalPages;
    private boolean last;

    @java.lang.SuppressWarnings("all")
    public List<T> getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    public int getPage() {
        return this.page;
    }

    @java.lang.SuppressWarnings("all")
    public int getSize() {
        return this.size;
    }

    @java.lang.SuppressWarnings("all")
    public long getTotalElements() {
        return this.totalElements;
    }

    @java.lang.SuppressWarnings("all")
    public int getTotalPages() {
        return this.totalPages;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isLast() {
        return this.last;
    }

    @java.lang.SuppressWarnings("all")
    public void setContent(final List<T> content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    public void setPage(final int page) {
        this.page = page;
    }

    @java.lang.SuppressWarnings("all")
    public void setSize(final int size) {
        this.size = size;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalElements(final long totalElements) {
        this.totalElements = totalElements;
    }

    @java.lang.SuppressWarnings("all")
    public void setTotalPages(final int totalPages) {
        this.totalPages = totalPages;
    }

    @java.lang.SuppressWarnings("all")
    public void setLast(final boolean last) {
        this.last = last;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PagedResponseDTO)) return false;
        final PagedResponseDTO<?> other = (PagedResponseDTO<?>) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getPage() != other.getPage()) return false;
        if (this.getSize() != other.getSize()) return false;
        if (this.getTotalElements() != other.getTotalElements()) return false;
        if (this.getTotalPages() != other.getTotalPages()) return false;
        if (this.isLast() != other.isLast()) return false;
        final java.lang.Object this$content = this.getContent();
        final java.lang.Object other$content = other.getContent();
        if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PagedResponseDTO;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPage();
        result = result * PRIME + this.getSize();
        final long $totalElements = this.getTotalElements();
        result = result * PRIME + (int) ($totalElements >>> 32 ^ $totalElements);
        result = result * PRIME + this.getTotalPages();
        result = result * PRIME + (this.isLast() ? 79 : 97);
        final java.lang.Object $content = this.getContent();
        result = result * PRIME + ($content == null ? 43 : $content.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PagedResponseDTO(content=" + this.getContent() + ", page=" + this.getPage() + ", size=" + this.getSize() + ", totalElements=" + this.getTotalElements() + ", totalPages=" + this.getTotalPages() + ", last=" + this.isLast() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PagedResponseDTO() {
    }

    @java.lang.SuppressWarnings("all")
    public PagedResponseDTO(final List<T> content, final int page, final int size, final long totalElements, final int totalPages, final boolean last) {
        this.content = content;
        this.page = page;
        this.size = size;
        this.totalElements = totalElements;
        this.totalPages = totalPages;
        this.last = last;
    }
}
