// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "certification")
public class Certification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;
    private String issuer;
    private String credentialId;
    private String url;
    private String remarks;
    @Column(name = "renewal_status")
    @Convert(converter = RenewalStatusConverter.class)
    private RenewalStatus renewalStatus;
    @Transient
    private CertificationStatus certificationStatus;
    @Column(name = "issue_date")
    private LocalDateTime issueDate;
    @Column(name = "expiry_date")
    private LocalDateTime expiryDate;
    @Column(name = "requested_on")
    private LocalDateTime requestedOn;
    @Column(name = "approved_on")
    private LocalDateTime approvedOn;
    @Column(name = "rejected_on")
    private LocalDateTime rejectedOn;
    @Column(name = "last_reminder_sent")
    private LocalDateTime lastReminderSent;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;


    @java.lang.SuppressWarnings("all")
    public static class CertificationBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String issuer;
        @java.lang.SuppressWarnings("all")
        private String credentialId;
        @java.lang.SuppressWarnings("all")
        private String url;
        @java.lang.SuppressWarnings("all")
        private String remarks;
        @java.lang.SuppressWarnings("all")
        private RenewalStatus renewalStatus;
        @java.lang.SuppressWarnings("all")
        private CertificationStatus certificationStatus;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime issueDate;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime expiryDate;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime requestedOn;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime approvedOn;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime rejectedOn;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime lastReminderSent;
        @java.lang.SuppressWarnings("all")
        private User user;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        CertificationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder issuer(final String issuer) {
            this.issuer = issuer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder credentialId(final String credentialId) {
            this.credentialId = credentialId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder url(final String url) {
            this.url = url;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder remarks(final String remarks) {
            this.remarks = remarks;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder renewalStatus(final RenewalStatus renewalStatus) {
            this.renewalStatus = renewalStatus;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder certificationStatus(final CertificationStatus certificationStatus) {
            this.certificationStatus = certificationStatus;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder issueDate(final LocalDateTime issueDate) {
            this.issueDate = issueDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder expiryDate(final LocalDateTime expiryDate) {
            this.expiryDate = expiryDate;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder requestedOn(final LocalDateTime requestedOn) {
            this.requestedOn = requestedOn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder approvedOn(final LocalDateTime approvedOn) {
            this.approvedOn = approvedOn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder rejectedOn(final LocalDateTime rejectedOn) {
            this.rejectedOn = rejectedOn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder lastReminderSent(final LocalDateTime lastReminderSent) {
            this.lastReminderSent = lastReminderSent;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Certification.CertificationBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Certification build() {
            return new Certification(this.id, this.title, this.issuer, this.credentialId, this.url, this.remarks, this.renewalStatus, this.certificationStatus, this.issueDate, this.expiryDate, this.requestedOn, this.approvedOn, this.rejectedOn, this.lastReminderSent, this.user, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Certification.CertificationBuilder(id=" + this.id + ", title=" + this.title + ", issuer=" + this.issuer + ", credentialId=" + this.credentialId + ", url=" + this.url + ", remarks=" + this.remarks + ", renewalStatus=" + this.renewalStatus + ", certificationStatus=" + this.certificationStatus + ", issueDate=" + this.issueDate + ", expiryDate=" + this.expiryDate + ", requestedOn=" + this.requestedOn + ", approvedOn=" + this.approvedOn + ", rejectedOn=" + this.rejectedOn + ", lastReminderSent=" + this.lastReminderSent + ", user=" + this.user + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Certification.CertificationBuilder builder() {
        return new Certification.CertificationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getIssuer() {
        return this.issuer;
    }

    @java.lang.SuppressWarnings("all")
    public String getCredentialId() {
        return this.credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public String getUrl() {
        return this.url;
    }

    @java.lang.SuppressWarnings("all")
    public String getRemarks() {
        return this.remarks;
    }

    @java.lang.SuppressWarnings("all")
    public RenewalStatus getRenewalStatus() {
        return this.renewalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public CertificationStatus getCertificationStatus() {
        return this.certificationStatus;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getIssueDate() {
        return this.issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getExpiryDate() {
        return this.expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getRequestedOn() {
        return this.requestedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getApprovedOn() {
        return this.approvedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getRejectedOn() {
        return this.rejectedOn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getLastReminderSent() {
        return this.lastReminderSent;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssuer(final String issuer) {
        this.issuer = issuer;
    }

    @java.lang.SuppressWarnings("all")
    public void setCredentialId(final String credentialId) {
        this.credentialId = credentialId;
    }

    @java.lang.SuppressWarnings("all")
    public void setUrl(final String url) {
        this.url = url;
    }

    @java.lang.SuppressWarnings("all")
    public void setRemarks(final String remarks) {
        this.remarks = remarks;
    }

    @java.lang.SuppressWarnings("all")
    public void setRenewalStatus(final RenewalStatus renewalStatus) {
        this.renewalStatus = renewalStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setCertificationStatus(final CertificationStatus certificationStatus) {
        this.certificationStatus = certificationStatus;
    }

    @java.lang.SuppressWarnings("all")
    public void setIssueDate(final LocalDateTime issueDate) {
        this.issueDate = issueDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setExpiryDate(final LocalDateTime expiryDate) {
        this.expiryDate = expiryDate;
    }

    @java.lang.SuppressWarnings("all")
    public void setRequestedOn(final LocalDateTime requestedOn) {
        this.requestedOn = requestedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setApprovedOn(final LocalDateTime approvedOn) {
        this.approvedOn = approvedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setRejectedOn(final LocalDateTime rejectedOn) {
        this.rejectedOn = rejectedOn;
    }

    @java.lang.SuppressWarnings("all")
    public void setLastReminderSent(final LocalDateTime lastReminderSent) {
        this.lastReminderSent = lastReminderSent;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public Certification() {
    }

    @java.lang.SuppressWarnings("all")
    public Certification(final Long id, final String title, final String issuer, final String credentialId, final String url, final String remarks, final RenewalStatus renewalStatus, final CertificationStatus certificationStatus, final LocalDateTime issueDate, final LocalDateTime expiryDate, final LocalDateTime requestedOn, final LocalDateTime approvedOn, final LocalDateTime rejectedOn, final LocalDateTime lastReminderSent, final User user, final LocalDateTime createdAt) {
        this.id = id;
        this.title = title;
        this.issuer = issuer;
        this.credentialId = credentialId;
        this.url = url;
        this.remarks = remarks;
        this.renewalStatus = renewalStatus;
        this.certificationStatus = certificationStatus;
        this.issueDate = issueDate;
        this.expiryDate = expiryDate;
        this.requestedOn = requestedOn;
        this.approvedOn = approvedOn;
        this.rejectedOn = rejectedOn;
        this.lastReminderSent = lastReminderSent;
        this.user = user;
        this.createdAt = createdAt;
    }
}
