// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.model;

import jakarta.persistence.*;
import org.hibernate.annotations.CreationTimestamp;
import java.time.LocalDateTime;

@Entity
@Table(name = "notifications")
public class Notification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String title;
    private String message;
    private String type; // REMINDER, RENEWAL_UPDATE, SYSTEM
    @Column(name = "is_read")
    private boolean isRead;
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;
    @Column(name = "read_at")
    private LocalDateTime readAt;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "certification_id")
    private Certification certification;

    @java.lang.SuppressWarnings("all")
    private static boolean $default$isRead() {
        return false;
    }


    @java.lang.SuppressWarnings("all")
    public static class NotificationBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String title;
        @java.lang.SuppressWarnings("all")
        private String message;
        @java.lang.SuppressWarnings("all")
        private String type;
        @java.lang.SuppressWarnings("all")
        private boolean isRead$set;
        @java.lang.SuppressWarnings("all")
        private boolean isRead$value;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        private LocalDateTime readAt;
        @java.lang.SuppressWarnings("all")
        private User user;
        @java.lang.SuppressWarnings("all")
        private Certification certification;

        @java.lang.SuppressWarnings("all")
        NotificationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder type(final String type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder isRead(final boolean isRead) {
            this.isRead$value = isRead;
            isRead$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder readAt(final LocalDateTime readAt) {
            this.readAt = readAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public Notification.NotificationBuilder certification(final Certification certification) {
            this.certification = certification;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public Notification build() {
            boolean isRead$value = this.isRead$value;
            if (!this.isRead$set) isRead$value = Notification.$default$isRead();
            return new Notification(this.id, this.title, this.message, this.type, isRead$value, this.createdAt, this.readAt, this.user, this.certification);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "Notification.NotificationBuilder(id=" + this.id + ", title=" + this.title + ", message=" + this.message + ", type=" + this.type + ", isRead$value=" + this.isRead$value + ", createdAt=" + this.createdAt + ", readAt=" + this.readAt + ", user=" + this.user + ", certification=" + this.certification + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static Notification.NotificationBuilder builder() {
        return new Notification.NotificationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isRead() {
        return this.isRead;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDateTime getReadAt() {
        return this.readAt;
    }

    @java.lang.SuppressWarnings("all")
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    public Certification getCertification() {
        return this.certification;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setRead(final boolean isRead) {
        this.isRead = isRead;
    }

    @java.lang.SuppressWarnings("all")
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setReadAt(final LocalDateTime readAt) {
        this.readAt = readAt;
    }

    @java.lang.SuppressWarnings("all")
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    public void setCertification(final Certification certification) {
        this.certification = certification;
    }

    @java.lang.SuppressWarnings("all")
    public Notification() {
        this.isRead = Notification.$default$isRead();
    }

    @java.lang.SuppressWarnings("all")
    public Notification(final Long id, final String title, final String message, final String type, final boolean isRead, final LocalDateTime createdAt, final LocalDateTime readAt, final User user, final Certification certification) {
        this.id = id;
        this.title = title;
        this.message = message;
        this.type = type;
        this.isRead = isRead;
        this.createdAt = createdAt;
        this.readAt = readAt;
        this.user = user;
        this.certification = certification;
    }
}
