// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.service;

import com.certifyme.app.dto.CertificationRequestDTO;

import com.certifyme.app.dto.CertificationResponseDTO;
import com.certifyme.app.dto.DashboardStatsDTO;
import com.certifyme.app.dto.PagedResponseDTO;
import com.certifyme.app.exception.ResourceNotFoundException;
import com.certifyme.app.mapper.CertificationMapper;
import com.certifyme.app.model.Certification;
import com.certifyme.app.model.CertificationStatus;
import com.certifyme.app.model.RenewalStatus;
import com.certifyme.app.model.User;
import com.certifyme.app.repository.CertificationRepository;
import com.certifyme.app.repository.UserRepository;
import com.certifyme.app.util.DateUtil;
import com.certifyme.app.util.ExcelExportUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import java.io.ByteArrayInputStream;
import java.time.LocalDateTime;
import java.util.List;

@Service
public class CertificationService {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(CertificationService.class);
    private final CertificationRepository repo;
    private final UserRepository userRepo;
    private final CertificationMapper mapper;
    private final NotificationService notificationService;

    public CertificationService(CertificationRepository repo, UserRepository userRepo, CertificationMapper mapper, NotificationService notificationService) {
        this.repo = repo;
        this.userRepo = userRepo;
        this.mapper = mapper;
        this.notificationService = notificationService;
    }

    public PagedResponseDTO<CertificationResponseDTO> getAll(Pageable pageable) {
        Page<Certification> page = repo.findAll(pageable);
        List<CertificationResponseDTO> dtos = mapper.toResponseDTOList(page.getContent());
        return new PagedResponseDTO<>(dtos, page.getNumber(), page.getSize(), page.getTotalElements(), page.getTotalPages(), page.isLast());
    }

    public List<CertificationResponseDTO> getAllForAdmin() {
        return mapper.toResponseDTOList(repo.findAllWithUser());
    }

    public CertificationResponseDTO saveCertification(Long userId, CertificationRequestDTO request) {
        User user = userRepo.findById(userId).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        Certification cert = mapper.toEntity(request);
        cert.setUser(user);
        cert = repo.save(cert);
        notificationService.createNotification(user, cert, "New Certification", "Certification \'" + cert.getTitle() + "\' was successfully added.", "SYSTEM");
        return mapper.toResponseDTO(cert);
    }

    public PagedResponseDTO<CertificationResponseDTO> getByUser(Long userId, Pageable pageable) {
        Page<Certification> page = repo.findByUserId(userId, pageable);
        List<CertificationResponseDTO> dtos = mapper.toResponseDTOList(page.getContent());
        return new PagedResponseDTO<>(dtos, page.getNumber(), page.getSize(), page.getTotalElements(), page.getTotalPages(), page.isLast());
    }

    public List<CertificationResponseDTO> getByUser(Long userId) {
        return mapper.toResponseDTOList(repo.findByUserId(userId));
    }

    public CertificationResponseDTO updateCertification(Long id, CertificationRequestDTO request) {
        Certification cert = repo.findById(id).orElseThrow(() -> new ResourceNotFoundException("Certification not found"));
        cert.setTitle(request.getTitle());
        cert.setIssuer(request.getIssuer());
        cert.setIssueDate(request.getIssueDate());
        cert.setExpiryDate(request.getExpiryDate());
        cert.setCredentialId(request.getCredentialId());
        cert.setUrl(request.getUrl());
        cert.setRemarks(request.getRemarks());
        return mapper.toResponseDTO(repo.save(cert));
    }

    public void deleteCertification(Long id) {
        if (!repo.existsById(id)) {
            throw new ResourceNotFoundException("Certification not found");
        }
        repo.deleteById(id);
    }

    public CertificationResponseDTO updateRenewalStatus(Long id, String statusStr) {
        Certification cert = repo.findById(id).orElseThrow(() -> new ResourceNotFoundException("Certification not found"));
        RenewalStatus status;
        try {
            status = RenewalStatus.valueOf(statusStr.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException("Invalid renewal status");
        }
        cert.setRenewalStatus(status);
        LocalDateTime now = LocalDateTime.now();
        if (status == RenewalStatus.PENDING) {
            cert.setRequestedOn(now);
            notificationService.createNotification(cert.getUser(), cert, "Renewal Requested", "Renewal requested for \'" + cert.getTitle() + "\'. Awaiting admin approval.", "RENEWAL_UPDATE");
        } else if (status == RenewalStatus.APPROVED) {
            cert.setApprovedOn(now);
            notificationService.createNotification(cert.getUser(), cert, "Renewal Approved", "Your renewal for \'" + cert.getTitle() + "\' has been approved.", "RENEWAL_UPDATE");
        } else if (status == RenewalStatus.REJECTED) {
            cert.setRejectedOn(now);
            notificationService.createNotification(cert.getUser(), cert, "Renewal Rejected", "Your renewal for \'" + cert.getTitle() + "\' was rejected. Check remarks.", "RENEWAL_UPDATE");
        }
        return mapper.toResponseDTO(repo.save(cert));
    }

    public CertificationResponseDTO sendReminder(Long id) {
        Certification cert = repo.findById(id).orElseThrow(() -> new ResourceNotFoundException("Certification not found"));
        cert.setLastReminderSent(LocalDateTime.now());
        cert = repo.save(cert);
        notificationService.createNotification(cert.getUser(), cert, "Action Required: Expiring Certification", "Your certification \'" + cert.getTitle() + "\' is expiring soon. Please renew it.", "REMINDER");
        return mapper.toResponseDTO(cert);
    }

    public List<CertificationResponseDTO> getExpiringSoon() {
        LocalDateTime now = LocalDateTime.now();
        LocalDateTime threshold = now.plusDays(30);
        return mapper.toResponseDTOList(repo.findExpiringSoon(now, threshold));
    }

    public List<CertificationResponseDTO> getExpired() {
        return mapper.toResponseDTOList(repo.findExpired(LocalDateTime.now()));
    }

    public List<CertificationResponseDTO> getPendingRenewals() {
        return mapper.toResponseDTOList(repo.findByRenewalStatus(RenewalStatus.PENDING));
    }

    public DashboardStatsDTO getDashboardStats(Long userId) {
        List<Certification> certs = repo.findByUserId(userId);
        long total = certs.size();
        long active = 0;
        long expiringSoon = 0;
        long expired = 0;
        long pendingRenewals = 0;
        for (Certification c : certs) {
            CertificationStatus status = DateUtil.computeCertificationStatus(c.getExpiryDate());
            if (status == CertificationStatus.ACTIVE) active++;
             else if (status == CertificationStatus.EXPIRING_SOON) expiringSoon++;
             else expired++;
            if (c.getRenewalStatus() == RenewalStatus.PENDING) pendingRenewals++;
        }
        double completion = 0.0;
        if (total > 0) {
            completion = ((double) active / total) * 100.0;
        }
        return DashboardStatsDTO.builder().totalCertifications(total).activeCertifications(active).expiringSoon(expiringSoon).expiredCertifications(expired).pendingRenewals(pendingRenewals).completionPercentage(completion).build();
    }

    public ByteArrayInputStream exportToExcel(Long userId) {
        List<CertificationResponseDTO> certs;
        if (userId == null) {
            certs = mapper.toResponseDTOList(repo.findAll());
        } else {
            certs = mapper.toResponseDTOList(repo.findByUserId(userId));
        }
        return ExcelExportUtil.generateCertificationReport(certs);
    }
}
