// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.service;

import com.certifyme.app.model.User;
import com.certifyme.app.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import java.util.List;

@Component
public class DataMigrationComponent implements CommandLineRunner {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(DataMigrationComponent.class);
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public DataMigrationComponent(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
    }

    @Override
    public void run(String... args) throws Exception {
        log.info("Checking for plaintext passwords to migrate...");
        List<User> users = userRepository.findAll();
        int migratedCount = 0;
        for (User user : users) {
            String pwd = user.getPassword();
            // A BCrypt hash starts with "$2a$" or "$2b$" or "$2y$" and is 60 chars long.
            if (pwd != null && !pwd.isEmpty() && !pwd.startsWith("$2a$")) {
                user.setPassword(passwordEncoder.encode(pwd));
                userRepository.save(user);
                migratedCount++;
            }
        }
        if (migratedCount > 0) {
            log.info("Successfully migrated {} passwords to BCrypt.", migratedCount);
        } else {
            log.info("No passwords needed migration.");
        }

        // Add a default admin if none exists so users can test OTP admin flow safely
        if (!userRepository.existsByEmail("verify.certifyme@gmail.com")) {
            User adminUser = User.builder()
                .firstName("Default")
                .lastName("Admin")
                .email("verify.certifyme@gmail.com")
                .password(passwordEncoder.encode("admin123"))
                .role(com.certifyme.app.model.Role.ADMIN)
                .age(30)
                .gender("Prefer not to say")
                .country("United States")
                .build();
            userRepository.save(adminUser);
            log.info(">>> Created default Admin account: verify.certifyme@gmail.com / password: admin123 <<<");
        }
    }
}
