// Generated by delombok at Mon Apr 06 14:12:28 IST 2026
package com.certifyme.app.service;

import com.certifyme.app.dto.PagedResponseDTO;
import com.certifyme.app.dto.UserResponseDTO;
import com.certifyme.app.exception.ResourceNotFoundException;
import com.certifyme.app.mapper.UserMapper;
import com.certifyme.app.model.Role;
import com.certifyme.app.model.User;
import com.certifyme.app.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.List;
import java.util.stream.Collectors;

@Service
public class UserService {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(UserService.class);
    private final UserRepository repo;
    private final UserMapper mapper;

    public UserService(UserRepository repo, UserMapper mapper) {
        this.repo = repo;
        this.mapper = mapper;
    }

    public UserResponseDTO getUserById(Long id) {
        User user = repo.findById(id).orElseThrow(() -> new ResourceNotFoundException("User not found"));
        return mapper.toResponseDTO(user);
    }

    @Transactional(readOnly = true)
    public PagedResponseDTO<UserResponseDTO> getAllStudents(Pageable pageable) {
        Page<User> page = repo.findByRole(Role.STUDENT, pageable);
        List<UserResponseDTO> dtos = page.getContent().stream().map(mapper::toResponseDTO).collect(Collectors.toList());
        return new PagedResponseDTO<>(dtos, page.getNumber(), page.getSize(), page.getTotalElements(), page.getTotalPages(), page.isLast());
    }

    @Transactional(readOnly = true)
    public List<UserResponseDTO> getAllUsers() {
        return repo.findAll().stream().map(mapper::toResponseDTO).collect(Collectors.toList());
    }
}
