spring.datasource.url=jdbc:postgresql://dpg-d76f31cr85hc73bjdgs0-a.singapore-postgres.render.com:5432/certifyme
spring.datasource.username=certifyme_user
spring.datasource.password=4vNdeGsQuZMFeht9FLd8eCA6N1UDUiva

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}